apiVersion: v1
kind: Service
metadata:
  name: hello
  labels:
    app: hello
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: hello
    tier: hello
  type: NodePort

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello
  labels:
    app: hello
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: hello
        tier: hello
    spec:
      containers:
      - image: sibendu/hello:latest
        name: hello
        ports:
        - containerPort: 80
          name: hello